### ISSUE TITLE
Will there be a version for zabbix 4.2?

### ISSUE THREAD

**Issue by eyekelly** [express42/zabbixapi#103]
Hey,

Just wondering if there are any plans to make it support zabbix 4.2
I'm getting unsupported error message.

**Comment by KrzysztofHajdamowicz** [comment]
Zabbix 4.2 is already supported, since module version 4.0.0

**Comment by fraenki** [comment]
> Zabbix 4.2 is already supported, since module version 4.0.0

It looks like only 4.0 is supported and all other versions will raise an error:

https://github.com/svdasein/zabbixapi/blob/820bfefea1d5717d5963e57356cbd60c9fb50d51/lib/zabbixapi/client.rb#L54-L56

**Comment by KrzysztofHajdamowicz** [comment]
> > Zabbix 4.2 is already supported, since module version 4.0.0
> 
> It looks like only 4.0 is supported and all other versions will raise an error:
> 
> https://github.com/svdasein/zabbixapi/blob/820bfefea1d5717d5963e57356cbd60c9fb50d51/lib/zabbixapi/client.rb#L54-L56

You were looking on old version of code.
Check latest tag or even master branch 😉

**Comment by fraenki** [comment]
> You were looking on old version of code.

Oops. Not sure how I ended at that outdated fork. :facepalm:
