### ISSUE TITLE
Updating media on a user

### ISSUE THREAD

**Issue by genebean** [express42/zabbixapi#24]
It seems that by switching from addmedia to update media that new entries will be created if needed but existing ones will be updated instead of duplicated. Any chance you would switch lib/zabbixapi/classes/users.rb to this or add a new method?
https://www.zabbix.com/documentation/2.4/manual/api/reference/user/updatemedia

**Comment by OscarBarrett** [comment]
Here's a PR to implement an update_medias method. #27

**Comment by evtuhovich** [comment]
Merged
