### ISSUE TITLE
Need method zbx.hostgroups.get_ids_by_host

### ISSUE THREAD

**Issue by meganuke19** [express42/zabbixapi#30]
Identically by zbx.templates.get_ids_by_host. It is necessary to work with several groups of the same host

**Comment by evtuhovich** [comment]
I do not understand what you want :-(

**Comment by meganuke19** [comment]
I need work with multiple hostgroups for zabbix hosts with api, add, change, remove groups.
I want methods identically methods for templates - delete, get_ids_by_host, mass_update & etc. Do you plan add these functionality for hostgroups?

**Comment by evtuhovich** [comment]
@meganuke19, i am ill now, so i'll look next week

**Comment by evtuhovich** [comment]
But you can do it with query method right now, or even send me a PR

**Comment by evtuhovich** [comment]
@meganuke19 i've add in 2.4.3 possibility to get groups of host and update them. See #31 for details.
