### ISSUE TITLE
Update sometimes won't

### ISSUE THREAD

**Issue by svdasein** [express42/zabbixapi#32]
In abbixapi 2.4.3 the hosts.update command sometimes fails to update the host. For example:

Zbx.hosts.update(
     :hostid => 11114,
     :host => 'MYHOSTNAME',
     :interfaces => [
                      {
                            :type => 1,
                            :main => 1,
                            :ip => '10.0.0.1',
                            :useip => 1
                      }
     ]
)

If the host already exists and already has some sort of address associated with it, this will fail and debug output will report  "equal keys" and "skip update".

I believe the reason for this is that the logic that tests for whether or not there are actually changes to perform only looks at the key side of the kv pairs that define the host.  It does not look into the value side, and in this case the value side is a whole structure so testing for differences would need to traverse and compare the entirety of the value side as well.

It might make sense to make the change sensing logic optional (or remove it), as doing complete inspection for difference detection would likely a good deal of complexity, and as the audience using this code is going to be people who know how to write code, I'm not sure how worth while comprehensive difference testing is.

**Comment by evtuhovich** [comment]
Fixed at 0c782812400cfca44cb9cbe56c02cd38ece88420. You can update to 2.4.4, and use

hosts.update({hash with data}, true)
