### ISSUE TITLE
Unable to add interfaces to a host

### ISSUE THREAD

**Issue by bastelfreak** [express42/zabbixapi#35]
Hi, I've got a node already configured with an agent interface and would like to add an snmp interface:
```ruby
      @zbx_api.hosts.update({
        hostid: zbx_host_id,
        interfaces: [
          {
            type: 3,
            main: 1,
            ip: 10.10.10.10,
            dns: '',
            port: 623,
            useip: 1
          },
          {
            type: 1,
            main: 1,
            ip: '10.111.2.50',
            dns: 'example.com',
            port: 10050,
            useip: 1
          }
        ]
      }, true)
```

The Zabbix API mentions that the update method replaces all interfaces, so I submit the existing one + the one I want to have added (first one). This results in an error method:

```
`_request': Server answer API error (ZabbixApi::ApiError)
 {
  "code": -32602,
  "message": "Invalid params.",
  "data": "Interface is linked to item \"Total memory\" on \"example.com\"."
}
 on request:
 {
  "method": "host.update",
  "params": [
    {
      "hostid": 10084,
      "interfaces": [
        {
          "type": 3,
          "main": 1,
          "ip": "10.111.20.50",
          "dns": "",
          "port": 623,
          "useip": 1
        },
        {
          "type": 1,
          "main": 1,
          "ip": "10.111.2.50",
          "dns": 'example.com',
          "port": 10050,
          "useip": 1
        }
      ]
    }
  ],
  "id": 26143,
  "jsonrpc": "2.0",
  "auth": "ea6ee299ab47fb17542938d1a92c7d6c"
}
```

I also tried to only submit the new interface, but this results in the same error.

* Can you tell me why the error is happening?
* Do I need to submit all existing interfaces in your gem or do you handle that internally?
* Do you've got any method that returns all existing interfaces on a node? I couldn't find one

**Comment by evtuhovich** [comment]
I afraid this is something inside zabbix, it try remove interface and then re-add it, as i think. You could try to manipulate interface objects throw zabbixapi zbx.query method. See zabbix API documentation for more details https://www.zabbix.com/documentation/2.4/manual/api/reference/hostinterface/create

**Comment by bastelfreak** [comment]
ah good tip, the zbx.query method is working. I don't need to submit all interfaces, only the one that I want to add (so there is no replace). Thank you so much!
