### ISSUE TITLE
Add support for Zabbix API version 3.0.0

### ISSUE THREAD

**Issue by davey** [express42/zabbixapi#44]
Zabbix 3.0.0 is out since about a week, but zabbixapi cannot connect to it:
`Zabbix API version: 3.0.0 is not support by this version of zabbixapi (ZabbixApi::ApiError)`

**Comment by goacid** [comment]
+1000

**Comment by evtuhovich** [comment]
@goacid, @davey Added in 2.4.7, i've just published it on rubygems.
