### ISSUE TITLE
graph history

### ISSUE THREAD

**Issue by mvam75** [express42/zabbixapi#46]
Are there any plans to implement grabbing of graph history?

**Comment by evtuhovich** [comment]
Did you mean https://www.zabbix.com/documentation/3.0/manual/api/reference/history/get ?

And what options do you need mostly for this method?

**Comment by mvam75** [comment]
Yeah, thats the one. I think the option that makes the most sense right now is limiting the results you get back.

**Comment by evtuhovich** [comment]
There is no big reason to craete history method. You could use `query` method from zabbixapi.

https://github.com/express42/zabbixapi#custom-queries

**Comment by mvam75** [comment]
i'll give that a try, thanks
