### ISSUE TITLE
hostgroup.massadd

### ISSUE THREAD

**Issue by Samgarr** [express42/zabbixapi#47]
Hello,
it is hostgroup mass methods covered with this gem or i am missing something? Eg. [this](https://www.zabbix.com/documentation/3.0/manual/api/reference/hostgroup/massadd?s[]=massadd) method. Thank you.

**Comment by evtuhovich** [comment]
Hi, @Samgarr 

massadd doesn't covered by this gem as a separate method, but you can use query method like this

```
zbx.query(
  :method => "hostgroup.massadd",
  :params => {
    :groups => [1, 2, 3], # and so on
  }
)
```
