### ISSUE TITLE
zabbixapi version

### ISSUE THREAD

**Issue by postgred** [express42/zabbixapi#66]
I think we need to support zabbixapi version 2.4.x for zabbix 2.4 with ruby 1.9.3, and version 3 with ruby 2 for zabbix 3.*. Any remarks?

**Comment by jrbeilke** [comment]
Ruby 1.9 and Zabbix 2.4 are both EOL at this point. There is Zabbix 2.2 LTS which we should probably still support until it drops later this year, but that could be maintained on the zabbixapi 2.2.x branch.

Also mentioned in #64

**Comment by jrbeilke** [comment]
json 2.0 was merged into master and a 3.0.x version is being cut for zabbixapi
