### ISSUE TITLE
excludeSearch query

### ISSUE THREAD

**Issue by raulvc** [express42/zabbixapi#71]
Apparently, the 'flag' data type can't be transcribed to json from a hash perspective... this makes negative searches hard...

https://www.zabbix.com/documentation/3.2/manual/api/reference_commentary

**Comment by Tomelin** [comment]
Hi dear,

I installed the zabbixapi but have the error in zabbixapi:

**S.O:** Centos7
**Zabbixapi is installed :**
gem install zabbixapi
Successfully installed zabbixapi-3.1.0
Parsing documentation for zabbixapi-3.1.0
1 gem installed
**Error:**
Error: Could not run: cannot load such file -- zabbixapi

What is problem?

**Comment by anapsix** [comment]
issue deprecated due to age
