### ISSUE TITLE
Include #connect timeout option in documentation 

### ISSUE THREAD

**Issue by jumbosushi** [express42/zabbixapi#74]
Thanks for a great gem!

Would be great if you guys can document about 'timeout' option when using #connect in rubydoc site.
I was about to use Ruby's Timeout (which is [dangerous](http://www.mikeperham.com/2015/05/08/timeout-rubys-most-dangerous-api/)) till I saw timeout option in the [client.rb](https://github.com/express42/zabbixapi/blob/d5be3da8c79ba13898ea62f53799232c2ddf1375/lib/zabbixapi/client.rb#L89)

**Comment by postgred** [comment]
Okay, I will add it to the doc.
