### ISSUE TITLE
Branch inconsistencies

### ISSUE THREAD

**Issue by chewi** [express42/zabbixapi#76]
I know these versions are deprecated but your older branches seem a bit wonky. zabbix2.2 is at some point after 2.4.9 while zabbix2.4 is at 2.4.5. Please straighten these out. zabbix2.0 seems okay. I'm not sure about zabbix1.8.

**Comment by jrbeilke** [comment]
Yea those older branches are a bit confusing. I did update the README to try and clarify things a bit, but other than that I'd have to leave it up to express42 on whether they want to rearrange those legacy branches.

> We support only two last versions of zabbix (3.0 and 3.2), so you should consider zabbixapi 0.6.x, 2.0.x, 2.2.x, and 2.4.x deprecated.

> Zabbix 1.8.2 (api version 1.2) | zabbixapi 0.6.x | branch zabbix1.8
Zabbix 1.8.9 (api version 1.3) | zabbixapi 0.6.x | branch zabbix1.8
Zabbix 2.0.x (api version 1.4 -> 2.0.10) | zabbixapi 2.0.x | branch zabbix2.0
Zabbix 2.2.x (api version 2.2.x) | zabbixapi 2.2.x | branch zabbix2.2
Zabbix 2.4.x (api version 2.2.x) | zabbixapi 2.4.x | branch zabbix2.4
Zabbix 3.0.x (api version 3.0.x) | zabbixapi 3.0.x | master
Zabbix 3.2.x (api version 3.2.x) | zabbixapi 3.0.x | master

**Comment by anapsix** [comment]
going to leave things as is, use tags to for reference
