### ISSUE TITLE
Extend this gem for zabbix api v 3.4

### ISSUE THREAD

**Issue by glafir** [express42/zabbixapi#81]
When we can get zabbixapi for Zabbix 3.4 ?

**Comment by glafir** [comment]
Temporatory deside is:
Find in _{Path-to-gem}/lib/zabbixapi/client.rb_
`unless api_version =~ /(2\.4|3\.[02])\.\d+/`
Change to
`unless api_version =~ /(2\.4|3\.[024])\.\d+/`
Then it work!

**Comment by tophercullen** [comment]
Second this. Zabbix 3.2 is technically 'unsupported'

**Comment by ottok** [comment]
While waiting for the fix to land on upstream you can put in your Gemfile:
`gem 'zabbixapi', :git => 'https://github.com/Seravo/zabbixapi.git', :branch => 'v3.1.0-fixed'`

Pull request open at: https://github.com/express42/zabbixapi/pull/85
