### ISSUE TITLE
https dropped in the client in versions tagged above 3.0.0

### ISSUE THREAD

**Issue by geoffr** [express42/zabbixapi#83]
The gem versions greater than 3.0.0 (tag) no longer have 'require 'net/https' in the client.rb file which means https based connections no longer work

Thanks

**Comment by fraenki** [comment]
This is no longer true for the most recent version. They've [switched](https://github.com/express42/zabbixapi/commit/ade147a4fe85d1a12c985f6df7b35034b6e35f44#diff-e4c256e6a91f4de6d474565ff8c53dc9) to using `net/http` which [supports HTTPS](https://docs.ruby-lang.org/en/2.0.0/Net/HTTP.html#class-Net::HTTP-label-HTTPS).

**Comment by gdubicki** [comment]
I have updated README accordingly.
