### ISSUE TITLE
New maintainer needed!

### ISSUE THREAD

**Issue by gdubicki** [express42/zabbixapi#93]
Sorry everyone but it turned out that we are not going to use Zabbix after all so I can't work on maintaining this module.

If anyone want to do this then please write a comment here so that the owner of the repo can approve your proposal.

**Comment by snehitgajjar** [comment]
Hi we do use the Zabbix extensively. We first thought about working on it on our forked repo but then thought it would be better if we keep it open source. Me and @Splyth have written `unit test` for the almost whole project. I would like to be one of the maintainers of this project.

**Comment by Splyth** [comment]
I'm willing to sign on too

**Comment by aladmit** [comment]
@gdubicki thanks for all you did for zabbixapi and good luck with next open source project 🙏 

@snehitgajjar @Splyth I`ve checked PR with tests and it looks cool! So a gave you write permissions to the project. Also, I need your emails to configure rubygems

**Comment by snehitgajjar** [comment]
@aladmit its `snehit.gajjar@gmail.com`. Thanks a lot for all the work you have done.

**Comment by Splyth** [comment]
@aladmit mine is splyth@gmail.com

**Comment by aladmit** [comment]
@snehitgajjar @Splyth Are you sure your accounts on rubygems use this emails? Rubygems says `Owner could not be found.`

**Comment by snehitgajjar** [comment]
@aladmit can you try once more?

**Comment by Splyth** [comment]
Same. I didn't have an account there yet. Should be fixed now

**Comment by aladmit** [comment]
@snehitgajjar @Splyth done 👍

**Comment by snehitgajjar** [comment]
Thanks a lot!
