### ISSUE TITLE
Undefined method error when zabbix has an unsupported version

### ISSUE THREAD

**Issue by d-vandyshev** [express42/zabbixapi#99]
For example :
[1] pry(#<ZabbixApi::Client>)> api_version
=> "3.2.6"

Result:
`
NoMethodError: undefined method `log' for #<ZabbixApi::Client:0x0000000001b5a878>
Did you mean?  load
from .... gems/ruby-2.6.3/gems/zabbixapi-4.1.1/lib/zabbixapi/client.rb:56:in `initialize'
`

**Comment by Splyth** [comment]
I think I'll just convert it to a `puts` statement The log is handy if you only want certain output
at certain log levels but in this case we'd always want to print it so I don't see any harm in it

**Comment by Bouke** [comment]
Fixed in 4.1.2!
